export default {
  INVITES: 'STREAM_MODALS/INVITES',
  MEMBERS: 'STREAM_MODALS/MEMBERS',
  FILTERS: 'STREAM_MODALS/FILTERS',
  WIDGETS: 'STREAM_MODALS/WIDGETS',
  USER: 'STREAM_MODALS/USER_PREVIEW',
  MORE: 'STREAM_MODALS/MORE',
  SELECT: 'GENERAL/SELECT',
}
