export default {
  INVITES: 'STREAM_MODALS/INVITES',
  ON_STAGE: 'STREAM_MODALS/ON_STAGE',
  FILTERS: 'STREAM_MODALS/FILTERS',
  WIDGETS: 'STREAM_MODALS/WIDGETS',
  MORE: 'STREAM_MODALS/MORE',
  SELECT: 'GENERAL/SELECT'
}
