export default {
  INVITES: 'STREAM_MODALS/INVITES',
  AUDIENCE: 'STREAM_MODALS/AUDIENCE',
  ON_STAGE: 'STREAM_MODALS/ON_STAGE',
  FILTERS: 'STREAM_MODALS/FILTERS',
  WIDGETS: 'STREAM_MODALS/WIDGETS',
}
